apiVersion: v1
kind: ConfigMap
metadata:
  name: kaamsetu-config
data:
  NODE_ENV: production
  CLIENT_ORIGIN: https://app.example.com
  PUBLIC_API_URL: https://app.example.com
  INTERNAL_API_URL: http://auth-service:4000/api
  COOKIE_SECURE: "true"
  NOTIFICATION_SERVICE_URL: http://booking-service:4001
  UPLOAD_DIR: /tmp/uploads/kyc
  PROFILE_UPLOAD_DIR: /tmp/uploads/profiles
  OBJECT_STORAGE_BUCKET: REPLACE_WITH_CLOUD_BUCKET
  OBJECT_STORAGE_REGION: us-east-1
  OBJECT_STORAGE_ENDPOINT: ""
  OBJECT_STORAGE_PUBLIC_URL: ""
  OBJECT_STORAGE_FORCE_PATH_STYLE: "false"
  RAZORPAY_AUTO_CAPTURE: "true"
