apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaamsetu
resources:
  - namespace.yaml
  - configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - auth-service/pdb.yaml
  - booking-service/deployment.yaml
  - booking-service/service.yaml
  - booking-service/hpa.yaml
  - booking-service/pdb.yaml
  - frontend/pdb.yaml
  - ingress.yaml
