import type { ProviderProfile } from './api';

export const demoProfiles: ProviderProfile[] = [
  { id: 'sample-1', name: 'Arjun Patel', category: 'electrician', city: 'Ahmedabad', service_area: 'Satellite · Vastrapur', description: 'Home wiring, lighting installation and quick electrical repairs.', verification_status: 'verified', rating: 4.9, review_count: 128, completed_jobs: 312, photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=720&q=80', preview: true },
  { id: 'sample-2', name: 'Meera Plumbing Co.', category: 'plumber', city: 'Ahmedabad', service_area: 'Bodakdev · Thaltej', description: 'Leak detection, bathroom fittings and dependable same-day repairs.', verification_status: 'verified', rating: 4.8, review_count: 96, completed_jobs: 241, photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=720&q=80', preview: true },
  { id: 'sample-3', name: 'ColourCraft Studio', category: 'painter', city: 'Ahmedabad', service_area: 'Prahlad Nagar · South Bopal', description: 'Interior painting and clean, carefully finished home makeovers.', verification_status: 'verified', rating: 4.9, review_count: 74, completed_jobs: 186, photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=720&q=80', preview: true },
  { id: 'sample-4', name: 'Saffron Table Catering', category: 'caterer', city: 'Ahmedabad', service_area: 'Ahmedabad city · Gandhinagar', description: 'Fresh Gujarati menus and thoughtful catering for gatherings.', verification_status: 'verified', rating: 4.9, review_count: 112, completed_jobs: 205, photo_url: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=720&q=80', preview: true },
  { id: 'sample-5', name: 'Aarav Appliance Care', category: 'technician', city: 'Ahmedabad', service_area: 'Navrangpura · Paldi', description: 'Qualified help for appliance installation and home technical repairs.', verification_status: 'verified', rating: 4.7, review_count: 58, completed_jobs: 143, photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=720&q=80', preview: true },
  { id: 'sample-6', name: 'BuildWell Materials', category: 'supplier', city: 'Ahmedabad', service_area: 'Citywide delivery', description: 'Trusted paint, plumbing and electrical supplies for home projects.', verification_status: 'verified', rating: 4.8, review_count: 83, completed_jobs: 229, photo_url: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=720&q=80', preview: true },
  { id: 'sample-7', name: 'Nisha Home Electric', category: 'electrician', city: 'Surat', service_area: 'Adajan · Vesu', description: 'Residential electrical maintenance and appliance connections.', verification_status: 'verified', rating: 4.8, review_count: 64, completed_jobs: 171, photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=720&q=80', preview: true },
  { id: 'sample-8', name: 'Harsh Decor & Paint', category: 'painter', city: 'Vadodara', service_area: 'Alkapuri · Manjalpur', description: 'Interior and exterior painting with transparent estimates.', verification_status: 'verified', rating: 4.8, review_count: 52, completed_jobs: 138, photo_url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=720&q=80', preview: true },
];