apiVersion: v1
kind: Service
metadata:
  name: booking-service
  labels:
    app.kubernetes.io/name: booking-service
    app.kubernetes.io/part-of: kaamsetu
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "4001"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: booking-service
  ports:
    - name: http
      port: 4001
      targetPort: http
